# Systems Of Equations As Matrices

We've worked a bit with matrices before, and the very cool thing about systems of equations is that we can represent them the same way.

We could represent our equations above as a matrix that looks like this:

```
[
    [2, 1, | 25],
    [3, 2, | 40]  
]
```

This is just a matrix that contains the coefficients and constants in our equations. We call this an augmented matrix, because it has both the constants and the coefficients. The line separates them, with constants to the right.

This matrix has three columns and two rows (where each row represents an equation in the system). The first column represents xx, the second represents yy, and the third is for the constants in the equations (which appear on the right of the = sign).

Systems of equations form the underpinnings of linear algebra, but we generally work with matrices like this one because it's easier for us to represent them.

The simplest way to represent a matrix in Python is with a NumPy array. A NumPy array can have rows and columns, just like a matrix.

In [1]:
import numpy as np

# Set the dtype to float to do float math with the numbers
matrix = np.asarray([
    [2, 1, 25],
    [3, 2, 40]  
], dtype=np.float32)

In [2]:
matrix

array([[  2.,   1.,  25.],
       [  3.,   2.,  40.]], dtype=float32)

In [5]:
# Multiply the first row of the matrix by 2.
matrix[0] = matrix[0] * 2

In [6]:
matrix

array([[  4.,   2.,  50.],
       [  3.,   2.,  40.]], dtype=float32)

In [8]:
# Subtract the second row from the first row.
matrix[0] = matrix[0] - matrix[1]

In [9]:
matrix

array([[  1.,   0.,  10.],
       [  3.,   2.,  40.]], dtype=float32)

In [11]:
# Subtract 3 times the first row from the second row.
matrix[1] = matrix[1] - (matrix[0] * 3)

In [12]:
matrix

array([[  1.,   0.,  10.],
       [  0.,   2.,  10.]], dtype=float32)

In [13]:
# Finally, divide the second row by 2 to get rid of the coefficient.
matrix[1] = matrix[1] / 2

In [14]:
matrix

array([[  1.,   0.,  10.],
       [  0.,   1.,   5.]], dtype=float32)

In [15]:
# More complex

In [99]:
import numpy as np

matrix = np.asarray([
    [1, 2, 0, 7],
    [0, 3, 3, 11],
    [1, 2, 2, 11]
], dtype=np.float32)

In [100]:
matrix[2] = matrix[2] - matrix[0]
matrix

array([[  1.,   2.,   0.,   7.],
       [  0.,   3.,   3.,  11.],
       [  0.,   0.,   2.,   4.]], dtype=float32)

In [101]:
matrix[2] = matrix[2] / 2
matrix

array([[  1.,   2.,   0.,   7.],
       [  0.,   3.,   3.,  11.],
       [  0.,   0.,   1.,   2.]], dtype=float32)

In [102]:
matrix[1] -= matrix[2] * 3
matrix

array([[ 1.,  2.,  0.,  7.],
       [ 0.,  3.,  0.,  5.],
       [ 0.,  0.,  1.,  2.]], dtype=float32)

In [103]:
# Divide the second row by 3
matrix[1] /= 3
matrix

array([[ 1.        ,  2.        ,  0.        ,  7.        ],
       [ 0.        ,  1.        ,  0.        ,  1.66666663],
       [ 0.        ,  0.        ,  1.        ,  2.        ]], dtype=float32)

In [104]:
# subtract 2x 2nd row from 1st
matrix[0] -= (matrix[1] * 2)
matrix

array([[ 1.        ,  0.        ,  0.        ,  3.66666675],
       [ 0.        ,  1.        ,  0.        ,  1.66666663],
       [ 0.        ,  0.        ,  1.        ,  2.        ]], dtype=float32)

In [ ]:
# more practice

In [128]:
# 3x + y = 3
# 4x - 3y = 17

matrix = np.asarray([
    [3, 1, 3],
    [4, -3, 17]
], dtype=np.float32)


In [129]:
matrix

array([[  3.,   1.,   3.],
       [  4.,  -3.,  17.]], dtype=float32)

In [130]:
matrix[0] *= 3
matrix

array([[  9.,   3.,   9.],
       [  4.,  -3.,  17.]], dtype=float32)

In [131]:
matrix[0] += matrix[1]
matrix

array([[ 13.,   0.,  26.],
       [  4.,  -3.,  17.]], dtype=float32)

In [132]:
matrix[0] /= 13
matrix

array([[  1.,   0.,   2.],
       [  4.,  -3.,  17.]], dtype=float32)

In [136]:
# 4x * 2 = 8, subtract 8 from both sides
matrix[1][0] = 0
matrix[1][2] = 9
matrix

array([[ 1.,  0.,  2.],
       [ 0., -3.,  9.]], dtype=float32)

In [137]:
matrix[1] /= -3
matrix

array([[ 1.,  0.,  2.],
       [-0.,  1., -3.]], dtype=float32)

In [139]:
# echelon form

matrix = np.asarray([
    [0, 0, 0, 7],
    [0, 0, 1, 11],
    [1, 2, 2, 11],
    [0, 5, 5, 1]
], dtype=np.float32)
matrix

array([[  0.,   0.,   0.,   7.],
       [  0.,   0.,   1.,  11.],
       [  1.,   2.,   2.,  11.],
       [  0.,   5.,   5.,   1.]], dtype=float32)

In [140]:
matrix[[0,2]]

array([[  0.,   0.,   0.,   7.],
       [  1.,   2.,   2.,  11.]], dtype=float32)

In [141]:
matrix[[0,2]] = matrix[[2,0]]
matrix

array([[  1.,   2.,   2.,  11.],
       [  0.,   0.,   1.,  11.],
       [  0.,   0.,   0.,   7.],
       [  0.,   5.,   5.,   1.]], dtype=float32)

In [143]:
# swap 2nd and 4th
matrix[[1,3]] = matrix[[3,1]]
matrix

array([[  1.,   2.,   2.,  11.],
       [  0.,   5.,   5.,   1.],
       [  0.,   0.,   0.,   7.],
       [  0.,   0.,   1.,  11.]], dtype=float32)

In [144]:
# swap 3nd and 4th
matrix[[2,3]] = matrix[[3,2]]
matrix

array([[  1.,   2.,   2.,  11.],
       [  0.,   5.,   5.,   1.],
       [  0.,   0.,   1.,  11.],
       [  0.,   0.,   0.,   7.]], dtype=float32)

In [145]:
# try to convert to reduced row echelon form
A = np.asarray([
    [10, 5, 20, 60],
    [3, 1, 0, 11],
    [8, 2, 2, 30],
    [0, 4, 5, 13]
], dtype=np.float32)
A

array([[ 10.,   5.,  20.,  60.],
       [  3.,   1.,   0.,  11.],
       [  8.,   2.,   2.,  30.],
       [  0.,   4.,   5.,  13.]], dtype=float32)

In [146]:
A[0] /= 10
A

array([[  1. ,   0.5,   2. ,   6. ],
       [  3. ,   1. ,   0. ,  11. ],
       [  8. ,   2. ,   2. ,  30. ],
       [  0. ,   4. ,   5. ,  13. ]], dtype=float32)

In [147]:
A[1] -= A[0] * 3
A

array([[  1. ,   0.5,   2. ,   6. ],
       [  0. ,  -0.5,  -6. ,  -7. ],
       [  8. ,   2. ,   2. ,  30. ],
       [  0. ,   4. ,   5. ,  13. ]], dtype=float32)

In [148]:
A[2] -= A[0] * 8
A

array([[  1. ,   0.5,   2. ,   6. ],
       [  0. ,  -0.5,  -6. ,  -7. ],
       [  0. ,  -2. , -14. , -18. ],
       [  0. ,   4. ,   5. ,  13. ]], dtype=float32)

In [149]:
A[1] /= -0.5
A

array([[  1. ,   0.5,   2. ,   6. ],
       [ -0. ,   1. ,  12. ,  14. ],
       [  0. ,  -2. , -14. , -18. ],
       [  0. ,   4. ,   5. ,  13. ]], dtype=float32)

In [150]:
A[2] -= A[1] * -2
A

array([[  1. ,   0.5,   2. ,   6. ],
       [ -0. ,   1. ,  12. ,  14. ],
       [  0. ,   0. ,  10. ,  10. ],
       [  0. ,   4. ,   5. ,  13. ]], dtype=float32)

In [151]:
A[0] -= A[1] * 0.5
A

array([[  1.,   0.,  -4.,  -1.],
       [ -0.,   1.,  12.,  14.],
       [  0.,   0.,  10.,  10.],
       [  0.,   4.,   5.,  13.]], dtype=float32)

In [152]:
A[3] -= A[1] * 4
A

array([[  1.,   0.,  -4.,  -1.],
       [ -0.,   1.,  12.,  14.],
       [  0.,   0.,  10.,  10.],
       [  0.,   0., -43., -43.]], dtype=float32)

In [153]:
A[2] /= 10
A

array([[  1.,   0.,  -4.,  -1.],
       [ -0.,   1.,  12.,  14.],
       [  0.,   0.,   1.,   1.],
       [  0.,   0., -43., -43.]], dtype=float32)

In [154]:
A[0] -= A[2] * -4
A

array([[  1.,   0.,   0.,   3.],
       [ -0.,   1.,  12.,  14.],
       [  0.,   0.,   1.,   1.],
       [  0.,   0., -43., -43.]], dtype=float32)

In [155]:
A[1] -= A[2] * 12
A

array([[  1.,   0.,   0.,   3.],
       [ -0.,   1.,   0.,   2.],
       [  0.,   0.,   1.,   1.],
       [  0.,   0., -43., -43.]], dtype=float32)

In [156]:
A[3] -= A[2] * -43
A

array([[ 1.,  0.,  0.,  3.],
       [-0.,  1.,  0.,  2.],
       [ 0.,  0.,  1.,  1.],
       [ 0.,  0.,  0.,  0.]], dtype=float32)

In [158]:
B = np.asarray([
    [5, -1, 3, 14],
    [0, 1, 2, 8],
    [0, -2, 5, 1],
    [0, 0, 6, 6]
], dtype=np.float32)
B

array([[  5.,  -1.,   3.,  14.],
       [  0.,   1.,   2.,   8.],
       [  0.,  -2.,   5.,   1.],
       [  0.,   0.,   6.,   6.]], dtype=float32)

In [159]:
B[0] /= 5
B

array([[ 1.        , -0.2       ,  0.60000002,  2.79999995],
       [ 0.        ,  1.        ,  2.        ,  8.        ],
       [ 0.        , -2.        ,  5.        ,  1.        ],
       [ 0.        ,  0.        ,  6.        ,  6.        ]], dtype=float32)

In [160]:
B[0] -= B[1] * -0.2
B

array([[ 1.       ,  0.       ,  1.       ,  4.4000001],
       [ 0.       ,  1.       ,  2.       ,  8.       ],
       [ 0.       , -2.       ,  5.       ,  1.       ],
       [ 0.       ,  0.       ,  6.       ,  6.       ]], dtype=float32)

In [161]:
B[2] -= B[1] * -2

In [162]:
B

array([[  1.       ,   0.       ,   1.       ,   4.4000001],
       [  0.       ,   1.       ,   2.       ,   8.       ],
       [  0.       ,   0.       ,   9.       ,  17.       ],
       [  0.       ,   0.       ,   6.       ,   6.       ]], dtype=float32)

In [163]:
B[2]/= 9
B

array([[ 1.        ,  0.        ,  1.        ,  4.4000001 ],
       [ 0.        ,  1.        ,  2.        ,  8.        ],
       [ 0.        ,  0.        ,  1.        ,  1.88888884],
       [ 0.        ,  0.        ,  6.        ,  6.        ]], dtype=float32)

In [164]:
B[0] -= B[2]
B

array([[ 1.        ,  0.        ,  0.        ,  2.51111126],
       [ 0.        ,  1.        ,  2.        ,  8.        ],
       [ 0.        ,  0.        ,  1.        ,  1.88888884],
       [ 0.        ,  0.        ,  6.        ,  6.        ]], dtype=float32)

In [165]:
B[1] -= B[2] * 2

In [166]:
B

array([[ 1.        ,  0.        ,  0.        ,  2.51111126],
       [ 0.        ,  1.        ,  0.        ,  4.22222233],
       [ 0.        ,  0.        ,  1.        ,  1.88888884],
       [ 0.        ,  0.        ,  6.        ,  6.        ]], dtype=float32)

In [167]:
B[3] -= B[2] * 6
B

array([[ 1.        ,  0.        ,  0.        ,  2.51111126],
       [ 0.        ,  1.        ,  0.        ,  4.22222233],
       [ 0.        ,  0.        ,  1.        ,  1.88888884],
       [ 0.        ,  0.        ,  0.        , -5.33333302]], dtype=float32)

In [168]:
B[3] /= -5.33333302
B

array([[ 1.        ,  0.        ,  0.        ,  2.51111126],
       [ 0.        ,  1.        ,  0.        ,  4.22222233],
       [ 0.        ,  0.        ,  1.        ,  1.88888884],
       [-0.        , -0.        , -0.        ,  1.        ]], dtype=float32)

In [169]:
B[0] -= B[3] * 2.51111126
B

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  1.        ,  0.        ,  4.22222233],
       [ 0.        ,  0.        ,  1.        ,  1.88888884],
       [-0.        , -0.        , -0.        ,  1.        ]], dtype=float32)

In [171]:
B[1] -= B[3] * 4.22222233
B

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ,  1.88888884],
       [-0.        , -0.        , -0.        ,  1.        ]], dtype=float32)

In [172]:
B[2] -= B[3] * 1.88888884
B

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [-0., -0., -0.,  1.]], dtype=float32)

In [180]:
B = np.asarray([
    [5, -1, 3, 14],
    [0, 1, 2, 8],
    [0, -2, 5, 1],
    [0, 0, 6, 6]
], dtype=np.float32)
B

array([[  5.,  -1.,   3.,  14.],
       [  0.,   1.,   2.,   8.],
       [  0.,  -2.,   5.,   1.],
       [  0.,   0.,   6.,   6.]], dtype=float32)

In [181]:
B[3] /= 6
B

array([[  5.,  -1.,   3.,  14.],
       [  0.,   1.,   2.,   8.],
       [  0.,  -2.,   5.,   1.],
       [  0.,   0.,   1.,   1.]], dtype=float32)

In [182]:
B[2] -= B[1] * -2
B

array([[  5.,  -1.,   3.,  14.],
       [  0.,   1.,   2.,   8.],
       [  0.,   0.,   9.,  17.],
       [  0.,   0.,   1.,   1.]], dtype=float32)

In [183]:
B[2] /= 9
B

array([[  5.        ,  -1.        ,   3.        ,  14.        ],
       [  0.        ,   1.        ,   2.        ,   8.        ],
       [  0.        ,   0.        ,   1.        ,   1.88888884],
       [  0.        ,   0.        ,   1.        ,   1.        ]], dtype=float32)

In [ ]:
# inconsistent because z cannot equal both 1.8 and 1 at the same time

In [184]:
# infinite solutions
A = np.asarray([
        [2, 4, 8, 20],
        [4, 8, 16, 40],
        [20, 5, 5, 10]
], dtype=np.float32)
A

array([[  2.,   4.,   8.,  20.],
       [  4.,   8.,  16.,  40.],
       [ 20.,   5.,   5.,  10.]], dtype=float32)

In [185]:
A[0] /= 2
A

array([[  1.,   2.,   4.,  10.],
       [  4.,   8.,  16.,  40.],
       [ 20.,   5.,   5.,  10.]], dtype=float32)

In [186]:
A[1] -= A[0] * 4
A

array([[  1.,   2.,   4.,  10.],
       [  0.,   0.,   0.,   0.],
       [ 20.,   5.,   5.,  10.]], dtype=float32)

In [187]:
A[2] -= A[0] * 20
A

array([[   1.,    2.,    4.,   10.],
       [   0.,    0.,    0.,    0.],
       [   0.,  -35.,  -75., -190.]], dtype=float32)

In [188]:
B = np.asarray([
        [1, 1, 1, 4],
        [3, -2, 5, 8],
        [8, -4, 5, 10]
        ], dtype=np.float32)
B

array([[  1.,   1.,   1.,   4.],
       [  3.,  -2.,   5.,   8.],
       [  8.,  -4.,   5.,  10.]], dtype=float32)

In [189]:
B[1] -= B[0] * 3
B

array([[  1.,   1.,   1.,   4.],
       [  0.,  -5.,   2.,  -4.],
       [  8.,  -4.,   5.,  10.]], dtype=float32)

In [190]:
B[2] -= B[0] * 8
B

array([[  1.,   1.,   1.,   4.],
       [  0.,  -5.,   2.,  -4.],
       [  0., -12.,  -3., -22.]], dtype=float32)

In [191]:
B[1] /= -5
B

array([[  1.        ,   1.        ,   1.        ,   4.        ],
       [ -0.        ,   1.        ,  -0.40000001,   0.80000001],
       [  0.        , -12.        ,  -3.        , -22.        ]], dtype=float32)

In [192]:
B[0] -= B[1]
B

array([[  1.        ,   0.        ,   1.39999998,   3.20000005],
       [ -0.        ,   1.        ,  -0.40000001,   0.80000001],
       [  0.        , -12.        ,  -3.        , -22.        ]], dtype=float32)

In [193]:
B[2] -= B[1] * -12
B

array([[  1.        ,   0.        ,   1.39999998,   3.20000005],
       [ -0.        ,   1.        ,  -0.40000001,   0.80000001],
       [  0.        ,   0.        ,  -7.80000019, -12.39999962]], dtype=float32)

In [194]:
B[2] /= -7.80000019

In [195]:
B

array([[ 1.        ,  0.        ,  1.39999998,  3.20000005],
       [-0.        ,  1.        , -0.40000001,  0.80000001],
       [-0.        , -0.        ,  1.        ,  1.58974349]], dtype=float32)

In [196]:
B[0] -= B[2] * 1.39999998
B

array([[ 1.        ,  0.        ,  0.        ,  0.97435927],
       [-0.        ,  1.        , -0.40000001,  0.80000001],
       [-0.        , -0.        ,  1.        ,  1.58974349]], dtype=float32)

In [197]:
B[1] -= B[2] * -0.40000001
B

array([[ 1.        ,  0.        ,  0.        ,  0.97435927],
       [-0.        ,  1.        ,  0.        ,  1.43589735],
       [-0.        , -0.        ,  1.        ,  1.58974349]], dtype=float32)