In [11]:
import numpy as np
import random

In [2]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
a.transpose()

array([1, 2, 3])

In [4]:
a.shape = (3, 1)

In [5]:
a

array([[1],
       [2],
       [3]])

In [6]:
a.transpose()

array([[1, 2, 3]])

In [20]:
v = np.array([random.random() for i in range(12)])

In [21]:
v

array([ 0.01947407,  0.97507513,  0.11118474,  0.08989993,  0.84109898,
        0.58096873,  0.45765437,  0.88077996,  0.28642177,  0.0626973 ,
        0.55577169,  0.66034873])

In [27]:
v.shape = (12,1)

In [28]:
v

array([[ 0.01947407],
       [ 0.97507513],
       [ 0.11118474],
       [ 0.08989993],
       [ 0.84109898],
       [ 0.58096873],
       [ 0.45765437],
       [ 0.88077996],
       [ 0.28642177],
       [ 0.0626973 ],
       [ 0.55577169],
       [ 0.66034873]])

In [29]:
v2 = np.array([random.random() for i in range(10)])
v2

array([ 0.89344638,  0.18887025,  0.3692661 ,  0.18601605,  0.99453585,
        0.91032159,  0.49266606,  0.28357788,  0.45691534,  0.72858578])

In [31]:
v2.shape = (1,10)

In [32]:
v2

array([[ 0.89344638,  0.18887025,  0.3692661 ,  0.18601605,  0.99453585,
         0.91032159,  0.49266606,  0.28357788,  0.45691534,  0.72858578]])

In [34]:
np.dot(v, v2)

array([[ 0.01739904,  0.00367807,  0.00719111,  0.00362249,  0.01936766,
         0.01772767,  0.00959421,  0.00552242,  0.008898  ,  0.01418853],
       [ 0.87117735,  0.18416269,  0.36006219,  0.18137963,  0.96974717,
         0.88763194,  0.48038642,  0.27650974,  0.44552679,  0.71042587],
       [ 0.09933761,  0.02099949,  0.04105676,  0.02068215,  0.11057721,
         0.10121387,  0.05477695,  0.03152953,  0.05080201,  0.08100762],
       [ 0.08032077,  0.01697942,  0.033197  ,  0.01672283,  0.08940871,
         0.08183785,  0.04429065,  0.02549363,  0.04107666,  0.06549981],
       [ 0.75147684,  0.15885858,  0.31058934,  0.15645791,  0.83650309,
         0.76567056,  0.41438092,  0.23851707,  0.38431103,  0.61281276],
       [ 0.51906441,  0.10972771,  0.21453206,  0.10806951,  0.57779423,
         0.52886838,  0.28622358,  0.16474988,  0.26545353,  0.42328556],
       [ 0.40888964,  0.0864373 ,  0.16899625,  0.08513106,  0.45515368,
         0.41661265,  0.22547077,  0.12978066